[package]
name = "newsletter_server"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "newsletter_server"

[dependencies]
actix-web = "4.0.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }